<?php echo $this->form()->openTag($beerForm); ?>
  <?php if ($beerForm->has('id')): ?>
    <div class="form_element">
      <?php echo $this->formRow($beerForm->get('id')) ?>
     </div>
  <?php endif;?>
  
  <div class="form_element">
      <?php echo $this->formRow($beerForm->get('name')); ?>
  </div>

  <div class="form_element">
      <?php echo $this->formRow($beerForm->get('style')); ?>
  </div>

  <div class="form_element">
      <?php echo $this->formRow($beerForm->get('img')); ?>
  </div>



  <?php echo $this->formElement($beerForm->get('send')) ?>

<?php echo $this->form()->closeTag() ?>
